server:
  port: 8092

spring:
  application:
    name: CategoryService
  data:
    mongodb:
      uri: mongodb://localhost:27017/categorydb  # MongoDB serverin? qo?ulma

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka serverinin URL-i
